/*********************************************************************
 *
 * Copyright © 2025–2026 Dankest, LLC
 * Based on XChain Platform by Dankest, LLC – https://dankest.llc
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * This file is part of XChain Platform. Licensed under the GNU Affero
 * General Public License v3.0 or later; see LICENSE.md. A commercial
 * license (without AGPL source-disclosure terms) is available -
 * contact legal@dankest.llc.
 *
 **********************************************************************
 *
 * XChain Explorer - registering the express listeners
 *
 * Every listener the explorer answers on, mounted in one place. The ORDER these
 * register in is what decides which one answers a request, so the calls stay in one
 * list and each group is its own step below it.
 *
 * HOW THIS ATTACHES
 *
 * The methods are authored as a class body and exported as that class's prototype,
 * so XChainExplorer.js can copy them onto its own prototype verbatim (see
 * explorer/install.js). Nothing here is ever instantiated: `this` is the explorer
 * instance at call time, exactly as it was when these methods sat inline.
 *
 * setupUrls() hands in the host bag: express and fs as THIS instance's require map
 * holds them, plus the config-env view. They travel with the call rather than being
 * stored in this module, because the suites build explorers through proxyquire and a
 * module-level binding would hand whichever instance was built last to every
 * explorer in the process.
 *
 ********************************************************************/

'use strict';

const path = require('path');
const { routeTables } = require('./routes/index.js');
const { buildFeeQuoteLimiter, buildPreflightPostLimiter, buildBatchLimiter,
        buildCheckpointLimiters, buildProofLimiters, buildVmQueryLimiter } = require('./mount/limiters.js');

// Body-parser ceiling for POST /{COIN}/api/preflight. Above
// MAX_PREFLIGHT_PARAMS_LENGTH (explorer/fees_preflight.js, where the route that
// enforces it lives) because JSON string escaping can inflate a payload before the
// length check there can see it; the real refusal is the character check on the
// decoded value, not this.
const PREFLIGHT_BODY_LIMIT = '1mb';

class RouteMounts {

    // Build the route table and register the express listeners it implies.
    mountRoutes(host){

        // Every URL the explorer answers. The tables are data and live in
        // src/explorer/routes/; what stays here is the mounting, because the ORDER
        // these listeners register in is what decides which one answers a request,
        // and that order is only visible when the calls sit in one list.
        let urls = routeTables();

        this.mountAssetRoutes(host, urls);
        this.mountTransactionRedirect();
        this.mountFileRawRoute();
        const feeQuoteLimiter = this.mountFeeQuoteRoutes(host);
        this.mountPreflightPostRoute(host);
        this.mountBatchRoutes(host, feeQuoteLimiter);
        const checkpointListLimiter = this.mountCheckpointRoutes(host);
        this.mountProofRoutes(host, checkpointListLimiter);
        this.mountContractCallRoute(host);
        this.mountCatchAllRoute();

        return urls;
    }

    // The listeners that hand back a file rather than query the database: icons and
    // relayed token content, the OpenAPI document, the Font Awesome package, and one
    // mount per directory in the static table.
    mountAssetRoutes(host, urls){
        const { express, fs } = host;
        // Listener for icon requests: token icons resolved and cached locally.
        this.app.use('/icon', (req, res) => { this.processIconRequest(req, res); });
        // Listener for relay requests: fetches remote token content on a page's behalf.
        this.app.use('/relay', (req, res) => { this.processRelayRequest(req, res); });

        // Machine-readable API spec (OpenAPI 3.1). Regenerated by docs/openapi.build.js;
        // test/unit/http/openapi_coverage.test.js keeps it in lockstep with the urls tables.
        // The legacy docs-page URL answers the same bytes, ahead of the /json static mount.
        const sendOpenapiSpec = (req, res) => {
            if(!this.openapiSpec)
                this.openapiSpec = fs.readFileSync(path.join(__dirname, '..', '..', 'docs/openapi.json'));
            res.set('Cache-Control', 'public, max-age=3600');
            res.type('application/json').send(this.openapiSpec);
        };
        this.app.get('/openapi.json', sendOpenapiSpec);
        this.app.get('/json/xchain-platform-api.json', sendOpenapiSpec);

        // Font Awesome Free is self-hosted from the npm package so icons work on
        // every deployment with no CDN, kit token, or per-deploy config. The CSS
        // references ../webfonts/, so both directories mount under /fontawesome.
        // test/unit/fontawesome-icons.test.js keeps template icon names inside
        // the Free set (plus the v4 shims and the local xchain.css glyphs).
        const faDir = path.dirname(require.resolve('@fortawesome/fontawesome-free/package.json'));
        this.app.use('/fontawesome/css',      express.static(path.join(faDir, 'css')));
        this.app.use('/fontawesome/webfonts', express.static(path.join(faDir, 'webfonts')));

        // Listeners for static file requests, one mount per directory in the static table.
        for(let directory of urls['static'])
            this.app.use('/' + directory, express.static(path.join(__dirname, '..', 'content', directory)))
    }

    // The one redirect the explorer serves.
    mountTransactionRedirect(){
        // /{COIN}/tx/{QUERY} is the near-universal convention for a transaction URL and
        // several clients build it that way (the wallet's post-send "view transaction"
        // link among them), but this explorer's only transaction route is
        // /{COIN}/transaction/{QUERY}, so those links 404'd.
        //
        // A 301 rather than serving transaction.html at both paths: one transaction must
        // have ONE canonical URL. Two live paths for the same resource would split it,
        // which matters now that pages emit a real <link rel="canonical">.
        // The querystring is carried across deliberately: setXChainParams() reads ?coin=
        // to resolve which chain the page is for, so dropping it here would silently
        // redirect to a different coin's transaction. Both segments are re-encoded, which
        // also keeps a traversal attempt (..%2F..) inside its path segment.
        this.app.get('/:coin/tx/:query', (req, res) => {
            let target = '/' + encodeURIComponent(req.params.coin) + '/transaction/' + encodeURIComponent(req.params.query);
            let qs     = req.originalUrl.indexOf('?');
            if(qs !== -1)
                target += req.originalUrl.substring(qs);
            res.redirect(301, target);
        });
    }

    mountFileRawRoute(){
        // Raw bytes for a FILE action, registered before the wildcard so the matcher
        // hits it first. Gated files return ciphertext as application/octet-stream for
        // client-side decryption (protocol/token-gated-content.md); non-gated files
        // serve stored bytes inline only for safe media MIME types (nft-standard.md).
        this.app.get('/:coin/api/file/:actionIndex/raw', (req, res) => { this.processFileRawRequest(req, res); });
    }

    // Returns the fee-quote limiter: /feeschedule shares this bucket but registers
    // later, after the batch routes, and moving it forward would change which
    // listener answers first.
    mountFeeQuoteRoutes(host){
        // Native-coin fee pre-flight + schedule: thin proxies to the colocated indexer's
        // read-only feequote/feeschedule JSON-RPC, so fee and oracle-price logic stays
        // single-sourced there. Registered before the wildcard so the matcher hits these
        // first. See xchain-documentation/concepts/gas.md (client pre-validation).

        const feeQuoteLimiter = buildFeeQuoteLimiter(host);
        this.app.get('/:coin/api/feequote',    feeQuoteLimiter, (req, res) => { this.processFeeQuoteRequest(req, res); });
        this.app.get('/:coin/api/oraclefeequote', feeQuoteLimiter, (req, res) => { this.processOracleFeeQuoteRequest(req, res); });
        this.app.get('/:coin/api/preflight',   (req, res) => { this.processPreflightRequest(req, res); });

        return feeQuoteLimiter;
    }

    mountPreflightPostRoute(host){
        const { express } = host;
        // POST sibling of the same pre-flight, not a second endpoint: identical inputs
        // and verdict, different transport. A GET cannot carry the largest legal input
        // at all, a 250-command BATCH running ~17,500 characters against Node's 16 KiB
        // request line; small actions keep the GET, which stays cacheable.

        // The body parser is mounted per-route because api.js applies a deliberately
        // tight 10kb global json() to everything else, and the limiter is per-route
        // because this is the only unauthenticated explorer surface taking a body
        // this large.
        const preflightPostLimiter = buildPreflightPostLimiter(host);
        // Limiter BEFORE the parser on purpose: a rate-limited caller is refused without
        // the server reading their megabyte first.
        this.app.post('/:coin/api/preflight',
            preflightPostLimiter,
            express.json({ limit: PREFLIGHT_BODY_LIMIT }),
            (req, res) => { this.processPreflightRequest(req, res); });
    }

    mountBatchRoutes(host, feeQuoteLimiter){
        // Batch reads: one POST answering up to BATCH_ADDRESS_MAX addresses, the shape
        // a multi-address wallet's cold open would otherwise ask for one request at a
        // time (five addresses x three chains was 30 balance reads plus 15 coinpay
        // reads in one minute, all counted separately by every ceiling in front of us).
        //
        // The explorer STILL fans out to the coin's tracker for each /address/ half
        // inside the request, so the fan-out is relocated behind the global 200-request
        // concurrency gate rather than removed: what changes is that the gate and the
        // rate limiter now see one caller-visible request instead of twenty, and the
        // work inside it is capped at BATCH_READ_CONCURRENCY in flight. Both halves are
        // produced by the same dispatcher that answers the per-address GETs (readApi
        // re-drives processRequest), so a batch entry and its GET can never drift.
        const batchLimiter = buildBatchLimiter(host);
        this.app.post('/:coin/api/balances', batchLimiter,
            (req, res) => { this.processBalancesBatchRequest(req, res).catch(err => this.sendUnhandled(err, req, res)); });
        this.app.post('/:coin/api/coinpay_obligations', batchLimiter,
            (req, res) => { this.processCoinpayObligationsBatchRequest(req, res).catch(err => this.sendUnhandled(err, req, res)); });

        this.app.get('/:coin/api/feeschedule', feeQuoteLimiter, (req, res) => { this.processFeeScheduleRequest(req, res); });
    }

    // Returns the checkpoint-list limiter: /checkpoints/range takes the same tier and
    // registers with the proof routes below.
    mountCheckpointRoutes(host){
        // Quorum-signed state checkpoints, the light-client verification surface.
        // /checkpoints lists the coin chain's latest; /checkpoint/:blockIndex/verify
        // re-verifies the 2f+1 oracle_publish signatures server-side AND returns what a
        // client needs to verify independently (canonical string, sigs, qualifying set).
        // Spec: xchain-documentation/protocol/actions/anchor.md

        const { checkpointListLimiter, checkpointVerifyLimiter } = buildCheckpointLimiters(host);
        this.app.get('/:coin/api/checkpoints', checkpointListLimiter, (req, res) => { this.processCheckpointsRequest(req, res); });
        this.app.get('/:coin/api/checkpoint/:blockIndex/verify', checkpointVerifyLimiter, (req, res) => { this.processCheckpointVerifyRequest(req, res); });
        // Self-synced hub-mirror observability: bootstrap +
        // watermark-lag state per coin, {enabled:false} in externally-maintained mode.
        this.app.get('/:coin/api/hub-mirror/status', (req, res) => { this.processHubMirrorStatusRequest(req, res); });

        return checkpointListLimiter;
    }

    mountProofRoutes(host, checkpointListLimiter){
        const { actionProofLimiter, validatorSetProofLimiter } = buildProofLimiters(host);
        // The balance proof is the same single-descent SMT shape as the contract-state
        // and locked-balance proofs, so it carries the same cap. The checkpoint range
        // is a bounded mirror read and takes its /checkpoints sibling's looser tier.
        this.app.get('/:coin/api/proof/balance/:address/:tick', actionProofLimiter, (req, res) => { this.processBalanceProofRequest(req, res); });
        this.app.get('/:coin/api/checkpoints/range', checkpointListLimiter, (req, res) => { this.processCheckpointsRangeRequest(req, res); });
        this.app.get('/:coin/api/proof/action/:actionIndex', actionProofLimiter, (req, res) => { this.processActionProofRequest(req, res); });
        this.app.get('/:coin/api/proof/validator-set', validatorSetProofLimiter, (req, res) => { this.processValidatorSetProofRequest(req, res); });
        // Contract-state proofs carry the action-proof limiter rather than running
        // uncapped: the handler is one 256-deep SMT descent (a sequential DB read per
        // non-empty level) plus two point reads, an unauthenticated CPU/IO amplifier
        // of the same class the action-proof cap exists for.
        this.app.get('/:coin/api/proof/contract-state/:contractIndex/:key', actionProofLimiter, (req, res) => { this.processContractStateProofRequest(req, res); });
        // Locked-balance (XCHAIN_ESC) proofs are the same single-descent shape as
        // the contract-state proof and get the same cap for the same reason.
        this.app.get('/:coin/api/proof/locked-balance/:address/:tick', actionProofLimiter, (req, res) => { this.processLockedBalanceProofRequest(req, res); });
    }

    mountContractCallRoute(host){
        // Read-only contract simulation (the platform's eth_call): runs a method in a
        // sandboxed xchain-vm against current state and discards all effects.
        // Default-off (EXPLORER_VM_QUERY_ENABLED) and capped far below the global
        // limit, since every call burns real CPU in the VM subprocess.
        const vmQueryLimiter = buildVmQueryLimiter(host);
        this.app.post('/:coin/api/contract/:contractIndex/call', vmQueryLimiter, (req, res) => { this.processContractCallRequest(req, res); });
    }

    mountCatchAllRoute(){
        // Catch-all: every request the listeners above did not take lands here,
        // including a static request that found no file.

        // Express 5 / path-to-regexp v8 rejects a bare '*' at startup, and
        // the wildcard MUST be braced ('/{*path}') to match the bare root '/': the
        // unbraced form requires a trailing segment, dropping '/' through to the
        // JSON-RPC router as a -32600.
        this.app.get('/{*path}', (req, res) => { this.processRequest(req, res).catch(err => this.sendUnhandled(err, req, res)); });
    }
}

module.exports = { methods: RouteMounts.prototype, PREFLIGHT_BODY_LIMIT };
